name = "api"
compatibility_date = "2024-09-08"
# compatibility_flags = [ "nodejs_compat" ]

workers_dev = true

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = 'R2_BUCKET_MY_CAROUSEL'
bucket_name = 'my-carousel'
preview_bucket_name = 'my-carousel'

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "my-carousel"
database_id = "d911e4b0-8a8a-4314-b4d3-c81c49524cae"

# [ai]
# binding = "AI"
